# Path to your oh-my-zsh configuration.
ZSH=$HOME/.zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="tomb"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(command-not-found capistrano cp debian django gem git git-extras git-remote-branch history kate lol python rake rsync ruby rvm screen urltools vagrant)

# Load oh-my-zsh
[[ -e $ZSH/oh-my-zsh.sh ]] && source $ZSH/oh-my-zsh.sh

# Load environment variables
[[ -e $HOME/.env ]] && source $HOME/.env

# Load aliases from a shell-neutral aliases file
[[ -f $HOME/.aliases ]] && source $HOME/.aliases

# Disable shared history (set in oh-my-zsh/lib/history.zsh)
unsetopt share_history

# Load regexp-replace function
autoload -U regexp-replace

# Load Ruby Version Manager
RVM=$HOME/.rvm/scripts/rvm
[[ -e $RVM ]] && source $RVM

# Ensure that 's' completes in the same manner as 'ssh'
compdef s=ssh

