call pathogen#infect()
set t_Co=256
colorscheme ir_black
syntax on
filetype plugin indent on
set nocompatible
set number
set background=dark
highlight LineNr ctermfg=grey
set expandtab
set shiftwidth=2
set softtabstop=2
set omnifunc=syntaxcomplete#Complete
